/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProyectoFinal;

import java.awt.TextArea;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;

/**
 *
 * @author jeiso
 */
public class Inventarios extends javax.swing.JFrame {

    /**
     * Creates new form Inventarios
     */
    public Inventarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        btnAgregarP = new javax.swing.JButton();
        btnVerP = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblProductosM = new javax.swing.JLabel();
        lblCantidadP = new javax.swing.JLabel();
        textArea = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregarP.setText("Agregar Productos ");
        btnAgregarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnAgregarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        btnVerP.setText("Ver Producto ");
        btnVerP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnVerP, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, -1, -1));

        btnSalir.setText("Salir");
        pnlPrincipal.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, -1, -1));

        lblProductosM.setText("#Productos");
        pnlPrincipal.add(lblProductosM, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, -1, -1));

        lblCantidadP.setText("0");
        pnlPrincipal.add(lblCantidadP, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        textArea.setViewportView(jTextArea1);

        pnlPrincipal.add(textArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 410, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPActionPerformed
        // TODO add your handling code here:
        Productos np = new Productos(this,true);
        np.setLocationRelativeTo(null);
        np.setVisible(true);
        if (np.getEstado()) {
            try {
                FileWriter fw = new FileWriter("Inventarios.txt",true);
                BufferedWriter bw = new BufferedWriter(fw);
                bw.write(np.getCodigo()+" , "+np.getNombre()+" , "+np.getCantidad()+" , "+np.getPInterno()+" , "+np.getPVenta()+"/n" );
                bw.close();
                fw.close();
            } catch (IOException e) {
                System.out.println("Error //"+ e.getMessage());
            }
                                                                                      
        }
        
    }//GEN-LAST:event_btnAgregarPActionPerformed

    private void btnVerPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPActionPerformed
        File file = new File("Inventarios.txt");
        ArrayList lista = new ArrayList <>();
        jTextArea1.setText(null);
        int cant = 0;
        try {
            Scanner scanner = new Scanner(file);
            
        } catch (FileNotFoundException e) {
            System.out.println("Error //"+ e.getMessage());
        }
        
        
    }//GEN-LAST:event_btnVerPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarP;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerP;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblCantidadP;
    private javax.swing.JLabel lblProductosM;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JScrollPane textArea;
    // End of variables declaration//GEN-END:variables
}
