/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProyectoFinal;

/**
 *
 * @author jesus
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        lblContrasenna = new javax.swing.JLabel();
        psfContrasenna = new javax.swing.JPasswordField();
        lblUsua = new javax.swing.JLabel();
        lblCandado = new javax.swing.JLabel();
        lblUsuarioP = new javax.swing.JLabel();
        rsbtnLogin = new rsbuttom.RSButtonMetro();
        rsbtnRegistrarse = new rsbuttom.RSButtonMetro();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPrincipal.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 200, -1));

        lblUsuario.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuario.setText("Usuario");
        lblUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblUsuario.setInheritsPopupMenu(false);
        pnlPrincipal.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 90, -1));

        lblContrasenna.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        lblContrasenna.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContrasenna.setText("Contraseña");
        pnlPrincipal.add(lblContrasenna, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 110, -1));
        pnlPrincipal.add(psfContrasenna, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 200, 20));

        lblUsua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuarioG.png"))); // NOI18N
        pnlPrincipal.add(lblUsua, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 130, 140));

        lblCandado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/candado.png"))); // NOI18N
        pnlPrincipal.add(lblCandado, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, -1, -1));

        lblUsuarioP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        pnlPrincipal.add(lblUsuarioP, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, -1));

        rsbtnLogin.setBackground(new java.awt.Color(0, 0, 0));
        rsbtnLogin.setText("Login");
        pnlPrincipal.add(rsbtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 100, 30));

        rsbtnRegistrarse.setBackground(new java.awt.Color(0, 0, 0));
        rsbtnRegistrarse.setText("Registrarse");
        rsbtnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rsbtnRegistrarseActionPerformed(evt);
            }
        });
        pnlPrincipal.add(rsbtnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 140, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo login.png"))); // NOI18N
        pnlPrincipal.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 874, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rsbtnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rsbtnRegistrarseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rsbtnRegistrarseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCandado;
    private javax.swing.JLabel lblContrasenna;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblUsua;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuarioP;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPasswordField psfContrasenna;
    private rsbuttom.RSButtonMetro rsbtnLogin;
    private rsbuttom.RSButtonMetro rsbtnRegistrarse;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
